variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2
   CONTAINER_IMAGE: gitlab.misasa.okayama-u.ac.jp:4567/$CI_PROJECT_PATH

stages:
  - build
  - test

test_app:
   image: gitlab.misasa.okayama-u.ac.jp:4567/$CI_PROJECT_PATH:latest
   stage: test
   script:
     - pwd

build_docker_image:
   services:
     - docker:dind
   before_script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.misasa.okayama-u.ac.jp:4567
   stage: build
   script:
     - docker build --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
     - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
     - docker push $CONTAINER_IMAGE:latest
   only:
     - master
   when: manual