version: '2'
services:
  postgres:
    image: postgres
  app:
    #build: .
    image: gitlab.misasa.okayama-u.ac.jp:4567/yyachi/medusa:latest
    working_dir: /srv/app/medusa
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #command: bundle exec rake db:create RAILS_ENV=test
    volumes:
      - .:/srv/app/medusa
    ports:
      - "3000:3000"
    depends_on:
      - postgres