version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/
  app:
    #build: .
    image: gitlab.misasa.okayama-u.ac.jp:4567/yyachi/medusa:latest
    working_dir: /srv/app/medusa
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #command: bundle exec rake db:create RAILS_ENV=test
    volumes:
      - .:/srv/app/medusa
      - stone_data:/srv/data
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  stone_data:
    driver_opts:
      type: nfs
      o: "addr=172.24.1.36,nfsvers=4"
      device: ":/"